---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/Docker/django2" # Location of package manifests
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/Docker/nginx" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/Docker/python" # Location of package manifests
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/Docker/reactjs" # Location of package manifests
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/Docker/go" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/Python/spotify" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/Docker/django2" # Location of package manifests
    schedule:
      interval: "weekly"
