# Specify the base image nginx:1.23-alpine
FROM nginx@sha256:593dac25b7733ffb7afe1a72649a43e574778bf025ad60514ef40f6b5d606247

# Create a working directory inside the image
WORKDIR /usr/share/nginx

# Copy directory files i.e all files
COPY . .
