# Specify the base image nginx:1.23-alpine
FROM nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305

# Create a working directory inside the image
WORKDIR /usr/share/nginx

# Copy directory files i.e all files
COPY . .
