# Specify the base image nginx:1.23-alpine
FROM nginx@sha256:104c7c5c54f2685f0f46f3be607ce60da7085da3eaa5ad22d3d9f01594295e9c

# Create a working directory inside the image
WORKDIR /usr/share/nginx

# Copy directory files i.e all files
COPY . .
