---
# This is a basic workflow to auto approve pull request from dependabot
name: "Auto approve"

# Controls when the workflow will run
on:
  # Triggers the workflow on pull events
  pull_request:
    types:
      - opened
      - synchronize

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Permissions needed to run the workflow (top level)
permissions:
  contents: read
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # approve the pull request 
  approve:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Harden runner
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      # Approve the Github pull request  
      - name: Approve
        run: |
          PR_AUTHOR=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.user.login')

          if [[ "$PR_AUTHOR" == "dependabot[bot]" ]]; then
            echo "This PR is from Dependabot. Auto-approving..."
            curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
              -d '{"event": "APPROVE"}'
          else
            echo "This PR is from $PR_AUTHOR. Skipping auto-approval."
          fi
