---
# This is a basic workflow to auto approve pull request from dependabot
name: "Auto approve"

# Controls when the workflow will run
on:
  # Triggers the workflow on pull events
  pull_request:
    types:
      - opened
      - synchronize

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Permissions needed to run the workflow (top level)
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # approve the pull request 
  approve:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Harden runner
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      # Approve the Github pull request  
      - name: Approve
        run: |
          echo "This PR is not from Dependabot. Skipping auto-approval."
