---
# This is a basic workflow to build and publish Docker images
name: "Docker CI/CD"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "Docker/**"
    # Publish semver tags as releases.
    tags: ['v*.*.*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Name of the app
  APP: emberjs

# Permissions needed to run the workflow (top level)
permissions:
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Buils the Docker image
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # This is used to complete the identity challenge
    permissions:
      contents: read
      packages: write
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ./Docker

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Harden runner
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            ghcr.io:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
  
      # Log in to the Container registry
      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 #v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      #Build en publish docker image
      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 #v4.1.1
        with:
          context: ./Docker/${{ env.APP }}
          file: ./Docker/${{ env.APP }}/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Publish Docker image
  publish:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # Define dependency's between jobs
    needs: build
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ./Docker
    # Setup env variables for the job
    environment:
      name: render
      url: "https://${{ env.APP }}example.onrender.com"

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Harden runner
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.render.com:443
            github.com:443

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
    
      # Call API to start redeploy
      - name: Redeploy
        uses: distributhor/workflow-webhook@b87727c1c92922034480e3e63c03af1ee79635d9 #v3.0.5
        env:
          webhook_url: ${{ secrets.RENDER_URL }}
          webhook_secret: "fP"
