---
# This is a basic workflow to deploy to a local Kubernetes (k3s) cluster
name: "Docker CI/CD"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "Docker/**"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the configuration (YAML) files 
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # This is used to complete the identity challenge
    permissions:
      contents: read
      packages: write
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ./Docker

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
  
      # Log in to the Container registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  # Deploy the config files to the k3s cluster
  publish:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # Define dependency's between jobs
    needs: build
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ./Docker

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
