---
# This is a basic workflow to deploy to a local Kubernetes (k3s) cluster
name: "Python CI/CD"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "Python/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Set environment variables
env:
  # Use folder for Python app
  FOLDER: ./Python/xata

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the configuration (YAML) files 
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ${{ env.FOLDER }}

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0

      # Install Python from matrix  
      - name: Install Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 #v3.1.2
        with:
          python-version: "${{ matrix.python-version }}"
 
      # Install dependencies from requirements 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt
