---
# This is a basic workflow to deploy to a local Kubernetes (k3s) cluster
name: "Python CI/CD"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "Python/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Set environment variables
env:
  # Use folder for Python app
  FOLDER: ./Python/xata

# Permissions needed to run the workflow (top level)
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the configuration (YAML) files 
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ${{ env.FOLDER }}

    # Setup matrix for OS and Python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Harden runner
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            sifon-lade-0z-s-workspace-h9pso8.eu-west-1.xata.sh:443

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      # Install Python from matrix  
      - name: Install Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 #v4.6.1
        with:
          python-version: "${{ matrix.python-version }}"
 
      # Install dependencies from requirements 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Run script
        run: python ./__main__.py --key ${{ secrets.XATA_KEY }}
